# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('total_amount', models.IntegerField()),
                ('bought_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Roomie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('email_address', models.EmailField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomiePaysForItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('form_of_payment', models.CharField(blank=True, max_length=500)),
                ('note', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house_finances.Item')),
                ('roomie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='house_finances.Roomie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomiePaysRoomie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('form_of_payment', models.CharField(blank=True, max_length=500)),
                ('note', models.TextField(blank=True)),
                ('roomie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='house_finances.Roomie')),
                ('to_roomie', models.ManyToManyField(related_name='_roomiepaysroomie_to_roomie_+', to='house_finances.Roomie')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
