# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house_finances', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomiepaysroomie',
            name='to_roomie',
        ),
        migrations.AddField(
            model_name='roomiepaysroomie',
            name='to_roomie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='house_finances.Roomie'),
            preserve_default=False,
        ),
    ]
