# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house_finances', '0002_auto_20151210_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('amount', models.IntegerField()),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='house_finances.Roomie')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='house_finances.Roomie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house_finances.Debt')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='roomiepaysforitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='roomiepaysforitem',
            name='roomie',
        ),
        migrations.RemoveField(
            model_name='roomiepaysroomie',
            name='roomie',
        ),
        migrations.RemoveField(
            model_name='roomiepaysroomie',
            name='to_roomie',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='RoomiePaysForItem',
        ),
        migrations.DeleteModel(
            name='RoomiePaysRoomie',
        ),
    ]
