# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house_finances', '0003_auto_20151210_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('amount', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='debt',
            name='name',
        ),
        migrations.AlterField(
            model_name='debt',
            name='creditor',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='house_finances.Roomie'),
        ),
        migrations.AddField(
            model_name='debt',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='house_finances.Item'),
            preserve_default=False,
        ),
    ]
