# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house_finances', '0004_auto_20151210_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomie',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='debt',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='debt',
            name='creditor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='house_finances.Roomie'),
        ),
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(),
        ),
    ]
