# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 05:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('house_finances', '0006_auto_20151211_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='date_began',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2015, 12, 12, 5, 46, 32, 266511, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debt',
            name='date_due',
            field=models.DateField(blank=True, default=datetime.datetime(2015, 12, 12, 5, 46, 39, 410668, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='date_bought',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2015, 12, 12, 5, 46, 43, 522331, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='date_paid',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2015, 12, 12, 5, 46, 48, 546242, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
