# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_finances', '0009_auto_20151211_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_bought',
            field=models.DateField(),
        ),
    ]
