# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_finances', '0010_auto_20151213_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debt',
            options={'ordering': ('-date_began', 'item')},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-date_bought', 'name')},
        ),
        migrations.AlterField(
            model_name='debt',
            name='date_began',
            field=models.DateField(),
        ),
    ]
